image: docker:git

stages:
  # - linting
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-runner -p $CI_ACCESS_PASSWORD $CI_REGISTRY

# pylint-job:
#   tags:
#     - docker_local
#   stage: linting
#   image: pipelinecomponents/pylint:latest
#   before_script: []
#   script:
#     - pylint **/*.py
#   allow_failure: true

build-job:
  tags:
    - docker_local
  stage: build
  script:
    - docker compose build
    - docker push $IMAGE_NAME

deploy-job:
  tags:
    - docker_local
  stage: deploy
  script:
    - cp ${ENV_FILE} .env
    - docker compose down --remove-orphans
    - docker compose pull
    - docker compose up -d
    - echo "DEPLOY OK"
  # only:
  #   - master
