image: docker:git

stages:
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-runner -p $CI_ACCESS_PASSWORD $CI_REGISTRY

build-job:
  tags:
    - docker_local
  stage: build
  script:
    - docker compose build
    - docker push $IMAGE_NAME
  only:
    - develop

deploy-job:
  tags:
    - docker_local
  stage: deploy
  script:
    - docker compose down --remove-orphans
    - docker compose pull
    - docker compose up -d
    - echo "DEPLOY OK"
  only:
    - master
