version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    image: "${IMAGE_NAME}"
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head &&
      python -m bot"   

volumes:
  pg_data:
