name: Deploy on Docker

on:
  pull_request:
    branches: [ "master" ]

env:
  COMPOSE_PROJECT_NAME: ${{ vars.COMPOSE_PROJECT_NAME }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  TZ: ${{ vars.TZ }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_URL: postgresql+psycopg://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@db/${{ secrets.DB_NAME }}
  GRAYLOG_HOST: ${{ secrets.GRAYLOG_HOST }}

jobs:
  lint:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  deploy:        
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        run: docker compose up -d --build
